name: Release BOM & Parent to GitHub Packages

on:
  push:
    branches: [ main ]                   # for testing
    tags: ['20*.*.*', '2025.*']          # e.g., 2025.08.16
  workflow_dispatch: {}

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      GH_OWNER: iotmining
      GH_REPO: iotmining/platform-build
      HAS_PAT: ${{ secrets.GH_PACKAGES_TOKEN != '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21 (and Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Maven settings
        run: |
          echo "Using settings at: $HOME/.m2/settings.xml"
          test -f "$HOME/.m2/settings.xml" || (echo "settings.xml missing" && exit 1)
          echo "===== servers block ====="
          awk '/<servers>/{p=1} p; /<\/servers>/{print; exit}' "$HOME/.m2/settings.xml" || true

      # --- Deploy BOM ---
      - name: Build/Publish BOM
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$HOME/.m2/settings.xml" -DskipTests -Dstyle.color=always \
                -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
                -DdeployAtEnd=false -Dmaven.deploy.skip=false \
                -f iotmining-bom/pom.xml \
                org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy
          else
            mvn -B -DskipTests -Dstyle.color=always \
                -f iotmining-bom/pom.xml clean verify
          fi

      # --- Deploy Parent ---
      - name: Build/Publish Parent
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$HOME/.m2/settings.xml" -DskipTests -Dstyle.color=always \
                -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
                -DdeployAtEnd=false -Dmaven.deploy.skip=false \
                -f iotmining-parent/pom.xml \
                clean org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy
          else
            mvn -B -DskipTests -Dstyle.color=always \
                -f iotmining-parent/pom.xml clean verify
          fi

      # --- Optional PAT fallback ---
      - name: Retry with PAT fallback
        if: ${{ failure() && env.HAS_PAT == 'true' }}
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          echo "FALLBACK: retrying deploy with PAT..."
          SETTINGS="$RUNNER_TEMP/settings.xml"
          cat > "$SETTINGS" <<XML
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${GH_ACTOR}</username>
                <password>${GH_PAT}</password>
              </server>
            </servers>
          </settings>
          XML

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always \
                -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
                -f iotmining-bom/pom.xml \
                org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy || exit 1

            mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always \
                -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
                -f iotmining-parent/pom.xml \
                org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy || exit 1
          else
            echo "Branch build failed earlier; PAT fallback only applies to tag publishes. Skipping."
          fi
