name: Release BOM & Parent to GitHub Packages

on:
  push:
    branches: [ main ]                 # keep during testing
    tags: ['20*.*.*', '2025.*']        # e.g., 2025.08.14
  workflow_dispatch: {}

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      # Optional PAT fallback: set GH_PACKAGES_TOKEN secret if your org blocks GITHUB_TOKEN
      HAS_PAT: ${{ secrets.GH_PACKAGES_TOKEN != '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21 (and Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Maven settings created
        run: |
          echo "Using settings at: $HOME/.m2/settings.xml"
          test -f "$HOME/.m2/settings.xml" || (echo "settings.xml missing" && exit 1)
          echo "===== settings.xml preview (servers block) ====="
          awk '/<servers>/{p=1} p; /<\/servers>/{print; exit}' "$HOME/.m2/settings.xml" || true

      # Optional: only deploy on tags; branch builds do a dry run (skipTests + -DaltDeploymentRepository to /dev/null)
      - name: Deploy BOM (tag) or build (branch)
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$HOME/.m2/settings.xml" -DskipTests -Dstyle.color=always clean deploy -f iotmining-bom/pom.xml
          else
            mvn -B -DskipTests -Dstyle.color=always -f iotmining-bom/pom.xml clean verify
          fi

      - name: Deploy Parent (tag) or build (branch)
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$HOME/.m2/settings.xml" -DskipTests -Dstyle.color=always clean deploy -f iotmining-parent/pom.xml
          else
            mvn -B -DskipTests -Dstyle.color=always -f iotmining-parent/pom.xml clean verify
          fi

      # Fallback to PAT if publish failed and PAT is present (commonly due to org policy)
      - name: Retry with PAT fallback
        if: ${{ failure() && env.HAS_PAT == 'true' }}
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          echo "FALLBACK: retrying deploy with PAT..."
          SETTINGS="$RUNNER_TEMP/settings.xml"
          cat > "$SETTINGS" <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${env.GH_ACTOR}</username>
                <password>${env.GH_PAT}</password>
              </server>
            </servers>
          </settings>
          XML

          # Re-run only on tags; if the failure was on branch, just exit 0 to not block CI
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always clean deploy -f iotmining-bom/pom.xml || exit 1
            mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always clean deploy -f iotmining-parent/pom.xml || exit 1
          else
            echo "Branch build failed earlier; PAT fallback is only for tag publishes. Skipping."
          fi
