name: Release BOM & Parent to GitHub Packages

on:
  push:
    branches: [ main ]                 # also run on main pushes (handy while testing)
    tags: ['20*.*.*', '2025.*']        # run on release tags like 2025.08.13
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Injects <server id="github"> with GITHUB_ACTOR / GITHUB_TOKEN into settings.xml
      - name: Setup Java 21 (with publish server creds)
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
          server-id: github                      # MUST match <distributionManagement><repository><id>
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      # Optional sanity check (don't remove settings.xml!)
      - name: Show settings path (debug)
        run: |
          echo "Using settings at: ${{ steps.setup-java.outputs.settings-path || '~/.m2/settings.xml' }}"
          grep -A2 '<id>github</id>' ~/.m2/settings.xml || true

      # Deploy BOM first
      - name: Deploy BOM
        run: mvn -B -DskipTests clean deploy -f iotmining-bom/pom.xml

      # Then Parent (which imports the BOM)
      - name: Deploy Parent
        run: mvn -B -DskipTests clean deploy -f iotmining-parent/pom.xml
