name: Reusable Container Build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build OCI with Spring Boot (Paketo)
        run: mvn -B -DskipTests spring-boot:build-image
      - name: Tag & Push
        run: |
          REF="${GITHUB_REF_NAME}"
          SHA="${GITHUB_SHA}"
          docker tag ghcr.io/iotmining/${{ inputs.image_name }}:${REF} ghcr.io/iotmining/${{ inputs.image_name }}:${SHA}
          docker push ghcr.io/iotmining/${{ inputs.image_name }}:${REF}
          docker push ghcr.io/iotmining/${{ inputs.image_name }}:${SHA}
