name: Snapshot Deploy (BOM & Parent)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Write Maven settings.xml for GH Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${env.GITHUB_ACTOR}</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          XML
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Deploy BOM (SNAPSHOT)
        run: mvn -B -s ~/.m2/settings.xml -DskipTests -pl :iotmining-bom -am versions:set -DnewVersion=2025.08.14-SNAPSHOT deploy

      - name: Deploy Parent (SNAPSHOT)
        run: mvn -B -s ~/.m2/settings.xml -DskipTests -pl :iotmining-parent -am versions:set -DnewVersion=2025.08.14-SNAPSHOT deploy
