name: Snapshot Deploy (BOM & Parent to GitHub Packages)

on:
  push:
    branches: [ main ]    # every push to main publishes SNAPSHOT
  workflow_dispatch: {}

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      GH_REPO: ${{ github.repository }}
      HAS_PAT: ${{ secrets.GH_PACKAGES_TOKEN != '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21 (and Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write clean Maven settings for GitHub Packages
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SETTINGS="$RUNNER_TEMP/gpr-settings.xml"
          cat > "$SETTINGS" <<XML
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${GH_ACTOR}</username>
                <password>${GH_TOKEN}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github-packages</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/${{ env.GH_REPO }}</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>github-plugins</id>
                    <url>https://maven.pkg.github.com/${{ env.GH_REPO }}</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github-packages</activeProfile>
            </activeProfiles>
          </settings>
          XML
          echo "GPR_SETTINGS=$SETTINGS" >> "$GITHUB_ENV"

      # ---- Critical: install the BOM locally BEFORE Parent (since it imports it) ----
      - name: Install BOM locally
        run: mvn -B -s "$GPR_SETTINGS" -DskipTests -Dstyle.color=always -f iotmining-bom/pom.xml clean install

      - name: Deploy BOM (SNAPSHOT)
        run: |
          mvn -B -s "$GPR_SETTINGS" -DskipTests -Dstyle.color=always \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
              -f iotmining-bom/pom.xml \
              org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy

      - name: Deploy Parent (SNAPSHOT)
        run: |
          mvn -B -s "$GPR_SETTINGS" -DskipTests -Dstyle.color=always \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
              -f iotmining-parent/pom.xml \
              org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy

      # Optional PAT fallback (if org blocks GITHUB_TOKEN for packages)
      - name: Retry with PAT fallback
        if: ${{ failure() && env.HAS_PAT == 'true' }}
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          echo "FALLBACK: retrying SNAPSHOT deploy with PAT…"
          SETTINGS="$RUNNER_TEMP/gpr-settings-pat.xml"
          cat > "$SETTINGS" <<XML
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GH_ACTOR}</username>
                <password>${GH_PAT}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github-packages</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/${{ env.GH_REPO }}</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github-packages</activeProfile>
            </activeProfiles>
          </settings>
          XML

          mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
              -f iotmining-bom/pom.xml \
              org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy

          mvn -B -s "$SETTINGS" -DskipTests -Dstyle.color=always \
              -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GH_REPO} \
              -f iotmining-parent/pom.xml \
              org.apache.maven.plugins:maven-deploy-plugin:3.1.3:deploy
